name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Specify your .NET SDK version

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore src/WebHost.csproj

      # Build the project
      - name: Build project
        run: dotnet build src/WebHost.csproj --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test src/WebHost.csproj --no-build --verbosity normal